version: '3.8'
services:
  redis-server:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - session-net

  app-1:
    build: .
    container_name: app-1
    hostname: app-1
    ports:
      - "8081:8080"
    environment:
      - SERVER_PORT=8080
      - HOSTNAME=app-1
    depends_on:
      - redis-server
    networks:
      - session-net

  app-2:
    build: .
    container_name: app-2
    hostname: app-2
    ports:
      - "8082:8080"
    environment:
      - SERVER_PORT=8080
      - HOSTNAME=app-2
    depends_on:
      - redis-server
    networks:
      - session-net

networks:
  session-net:
    driver: bridge
